version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    labels: [dependencies, ci]
  - package-ecosystem: npm
    directory: /desktop
    schedule:
      interval: monthly
    labels: [dependencies, desktop]
  - package-ecosystem: cargo
    directory: /relay-rust
    schedule:
      interval: monthly
    labels: [dependencies, relay]
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: monthly
    labels: [dependencies, android]
